CREATE TABLE email_outbox (
    id BINARY(16) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    template_type VARCHAR(40) NOT NULL,
    recipient VARCHAR(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    lead_id BINARY(16) NULL,
    deduplication_key VARCHAR(180) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    status VARCHAR(20) NOT NULL,
    delivery_count INT NOT NULL DEFAULT 0,
    available_at TIMESTAMP(6) NOT NULL,
    lease_token VARCHAR(36) NULL,
    locked_until TIMESTAMP(6) NULL,
    delivered_at TIMESTAMP(6) NULL,
    failure_code VARCHAR(40) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_email_outbox_deduplication UNIQUE (deduplication_key),
    CONSTRAINT fk_email_outbox_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL,
    CONSTRAINT chk_email_outbox_status CHECK (status IN ('PENDING', 'IN_PROGRESS', 'DELIVERED', 'FAILED')),
    CONSTRAINT chk_email_outbox_delivery_count CHECK (delivery_count >= 0),
    CONSTRAINT chk_email_outbox_template_type CHECK (template_type IN ('NEW_INQUIRY', 'QUALIFICATION_COMPLETED', 'QUALIFICATION_NEEDS_ATTENTION', 'PASSWORD_CHANGED')),
    CONSTRAINT chk_email_outbox_failure_code CHECK (failure_code IS NULL OR failure_code IN ('AUTHENTICATION', 'CONNECTION', 'TIMEOUT', 'REJECTED', 'INVALID_CONFIGURATION', 'UNEXPECTED')),
    INDEX idx_email_outbox_pending (status, available_at, created_at),
    INDEX idx_email_outbox_lease (status, locked_until)
);
